[2024-10-04 23:26:53,742] {processor.py:153} INFO - Started process (PID=91559) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:26:53,743] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:26:53,744] {logging_mixin.py:115} INFO - [2024-10-04 23:26:53,744] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:26:54,071] {logging_mixin.py:115} INFO - 
####### Class init: 2024-10-04 23:26:54 #######
[2024-10-04 23:26:54,071] {logging_mixin.py:115} INFO - Scrapping...
[2024-10-04 23:26:54,071] {logging_mixin.py:115} INFO - [2024-10-04 23:26:54,071] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-04 23:26:54,146] {logging_mixin.py:115} INFO - [2024-10-04 23:26:54,145] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:26:54,234] {logging_mixin.py:115} INFO - [2024-10-04 23:26:54,234] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:26:54,323] {logging_mixin.py:115} INFO - [2024-10-04 23:26:54,323] {logger.py:11} INFO - Driver [/home/kennedy/.wdm/drivers/chromedriver/linux64/129.0.6668.89/chromedriver-linux64/chromedriver] found in cache
[2024-10-04 23:27:23,746] {logging_mixin.py:115} INFO - [2024-10-04 23:27:23,746] {timeout.py:67} ERROR - Process timed out, PID: 91559
[2024-10-04 23:27:23,747] {logging_mixin.py:115} INFO - Erro ao acessar https://letterboxd.com/film/la-la-land/: DagBag import timeout for /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#reducing-dag-complexity, PID: 91559
[2024-10-04 23:28:52,278] {processor.py:153} INFO - Started process (PID=93887) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:28:52,283] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:28:52,283] {logging_mixin.py:115} INFO - [2024-10-04 23:28:52,283] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:28:52,514] {logging_mixin.py:115} INFO - 
####### Class init: 2024-10-04 23:28:52 #######
[2024-10-04 23:28:52,514] {logging_mixin.py:115} INFO - Scrapping...
[2024-10-04 23:28:52,514] {logging_mixin.py:115} INFO - [2024-10-04 23:28:52,514] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-04 23:28:52,602] {logging_mixin.py:115} INFO - [2024-10-04 23:28:52,602] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:28:52,713] {logging_mixin.py:115} INFO - [2024-10-04 23:28:52,713] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:28:52,805] {logging_mixin.py:115} INFO - [2024-10-04 23:28:52,805] {logger.py:11} INFO - Driver [/home/kennedy/.wdm/drivers/chromedriver/linux64/129.0.6668.89/chromedriver-linux64/chromedriver] found in cache
[2024-10-04 23:29:22,285] {logging_mixin.py:115} INFO - [2024-10-04 23:29:22,285] {timeout.py:67} ERROR - Process timed out, PID: 93887
[2024-10-04 23:29:22,286] {logging_mixin.py:115} INFO - Erro ao acessar https://letterboxd.com/film/la-la-land/: DagBag import timeout for /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#reducing-dag-complexity, PID: 93887
[2024-10-04 23:31:55,438] {processor.py:153} INFO - Started process (PID=96124) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:31:55,535] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:31:55,536] {logging_mixin.py:115} INFO - [2024-10-04 23:31:55,536] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:31:55,554] {logging_mixin.py:115} INFO - [2024-10-04 23:31:55,552] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:31:55,555] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:31:56,097] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.665 seconds
[2024-10-04 23:32:27,846] {processor.py:153} INFO - Started process (PID=96267) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:32:27,881] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:32:27,882] {logging_mixin.py:115} INFO - [2024-10-04 23:32:27,882] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:32:28,236] {logging_mixin.py:115} INFO - 
####### Class init: 2024-10-04 23:32:28 #######
[2024-10-04 23:32:28,236] {logging_mixin.py:115} INFO - Scrapping...
[2024-10-04 23:32:28,236] {logging_mixin.py:115} INFO - [2024-10-04 23:32:28,236] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-04 23:32:28,321] {logging_mixin.py:115} INFO - [2024-10-04 23:32:28,321] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:32:28,420] {logging_mixin.py:115} INFO - [2024-10-04 23:32:28,419] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:32:28,561] {logging_mixin.py:115} INFO - [2024-10-04 23:32:28,561] {logger.py:11} INFO - Driver [/home/kennedy/.wdm/drivers/chromedriver/linux64/129.0.6668.89/chromedriver-linux64/chromedriver] found in cache
[2024-10-04 23:33:54,171] {processor.py:153} INFO - Started process (PID=97053) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:33:54,184] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:33:54,185] {logging_mixin.py:115} INFO - [2024-10-04 23:33:54,185] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:33:54,204] {logging_mixin.py:115} INFO - [2024-10-04 23:33:54,202] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:33:54,205] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:33:54,349] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.188 seconds
[2024-10-04 23:34:26,422] {processor.py:153} INFO - Started process (PID=97084) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:34:26,435] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:34:26,436] {logging_mixin.py:115} INFO - [2024-10-04 23:34:26,435] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:34:26,449] {logging_mixin.py:115} INFO - [2024-10-04 23:34:26,447] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:34:26,449] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:34:26,628] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.211 seconds
[2024-10-04 23:35:06,979] {processor.py:153} INFO - Started process (PID=97115) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:35:07,099] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:35:07,100] {logging_mixin.py:115} INFO - [2024-10-04 23:35:07,100] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:35:07,120] {logging_mixin.py:115} INFO - [2024-10-04 23:35:07,117] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:35:07,121] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:35:08,477] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.504 seconds
[2024-10-04 23:35:34,512] {processor.py:153} INFO - Started process (PID=97207) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:35:34,513] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:35:34,515] {logging_mixin.py:115} INFO - [2024-10-04 23:35:34,514] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:35:34,909] {logging_mixin.py:115} INFO - 
####### Class init: 2024-10-04 23:35:34 #######
[2024-10-04 23:35:34,909] {logging_mixin.py:115} INFO - Scrapping...
[2024-10-04 23:35:34,909] {logging_mixin.py:115} INFO - [2024-10-04 23:35:34,909] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-04 23:35:34,989] {logging_mixin.py:115} INFO - [2024-10-04 23:35:34,989] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:35:35,176] {logging_mixin.py:115} INFO - [2024-10-04 23:35:35,176] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:35:35,376] {logging_mixin.py:115} INFO - [2024-10-04 23:35:35,376] {logger.py:11} INFO - Driver [/home/kennedy/.wdm/drivers/chromedriver/linux64/129.0.6668.89/chromedriver-linux64/chromedriver] found in cache
[2024-10-04 23:36:04,517] {logging_mixin.py:115} INFO - [2024-10-04 23:36:04,517] {timeout.py:67} ERROR - Process timed out, PID: 97207
[2024-10-04 23:36:04,518] {logging_mixin.py:115} INFO - Erro ao acessar https://letterboxd.com/film/la-la-land/: DagBag import timeout for /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#reducing-dag-complexity, PID: 97207
[2024-10-04 23:36:16,731] {processor.py:153} INFO - Started process (PID=98186) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:36:16,732] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:36:16,732] {logging_mixin.py:115} INFO - [2024-10-04 23:36:16,732] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:36:16,737] {logging_mixin.py:115} INFO - [2024-10-04 23:36:16,737] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:36:16,738] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:36:18,016] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.287 seconds
[2024-10-04 23:37:17,860] {processor.py:153} INFO - Started process (PID=98325) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:37:17,897] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:37:17,899] {logging_mixin.py:115} INFO - [2024-10-04 23:37:17,899] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:37:17,914] {logging_mixin.py:115} INFO - [2024-10-04 23:37:17,912] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:37:17,914] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:37:19,271] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.419 seconds
[2024-10-04 23:38:12,303] {processor.py:153} INFO - Started process (PID=98410) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:38:12,337] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:38:12,338] {logging_mixin.py:115} INFO - [2024-10-04 23:38:12,338] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:38:12,351] {logging_mixin.py:115} INFO - [2024-10-04 23:38:12,349] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:38:12,351] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:38:12,708] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.411 seconds
[2024-10-04 23:38:30,037] {processor.py:153} INFO - Started process (PID=98531) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:38:30,044] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:38:30,045] {logging_mixin.py:115} INFO - [2024-10-04 23:38:30,045] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:38:30,387] {logging_mixin.py:115} INFO - 
####### Class init: 2024-10-04 23:38:30 #######
[2024-10-04 23:38:30,387] {logging_mixin.py:115} INFO - Scrapping...
[2024-10-04 23:38:30,388] {logging_mixin.py:115} INFO - [2024-10-04 23:38:30,387] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-04 23:38:30,482] {logging_mixin.py:115} INFO - [2024-10-04 23:38:30,482] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:38:30,700] {logging_mixin.py:115} INFO - [2024-10-04 23:38:30,699] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:38:30,887] {logging_mixin.py:115} INFO - [2024-10-04 23:38:30,887] {logger.py:11} INFO - Driver [/home/kennedy/.wdm/drivers/chromedriver/linux64/129.0.6668.89/chromedriver-linux64/chromedriver] found in cache
[2024-10-04 23:38:48,934] {logging_mixin.py:115} INFO - [2024-10-04 23:38:48,932] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 159, in <module>
    create_movie_tasks(dag, movie_url)
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 123, in create_movie_tasks
    task_get_num_views = PythonOperator(
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 156, in __init__
    super().__init__(**kwargs)
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 880, in __init__
    self.dag = dag
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 990, in __setattr__
    super().__setattr__(key, value)
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1048, in dag
    dag.add_task(self)
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/venv/lib/python3.10/site-packages/airflow/models/dag.py", line 2130, in add_task
    raise AirflowException("DAG is missing the start_date parameter")
airflow.exceptions.AirflowException: DAG is missing the start_date parameter
[2024-10-04 23:38:48,935] {logging_mixin.py:115} INFO - 
####### Class end: 2024-10-04 23:38:48 #######
[2024-10-04 23:38:48,935] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:38:49,239] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 19.209 seconds
[2024-10-04 23:39:15,613] {processor.py:153} INFO - Started process (PID=99183) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:39:15,621] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:39:15,623] {logging_mixin.py:115} INFO - [2024-10-04 23:39:15,622] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:39:15,637] {logging_mixin.py:115} INFO - [2024-10-04 23:39:15,636] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:39:15,638] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:39:15,770] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.165 seconds
[2024-10-04 23:40:17,621] {processor.py:153} INFO - Started process (PID=99275) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:40:17,636] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:40:17,637] {logging_mixin.py:115} INFO - [2024-10-04 23:40:17,637] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:40:17,655] {logging_mixin.py:115} INFO - [2024-10-04 23:40:17,653] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:40:17,655] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:40:17,979] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.365 seconds
[2024-10-04 23:41:00,721] {processor.py:153} INFO - Started process (PID=99430) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:41:00,730] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:41:00,731] {logging_mixin.py:115} INFO - [2024-10-04 23:41:00,731] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:41:00,746] {logging_mixin.py:115} INFO - [2024-10-04 23:41:00,744] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:41:00,746] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:41:02,400] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.686 seconds
[2024-10-04 23:41:40,619] {processor.py:153} INFO - Started process (PID=99489) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:41:40,629] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:41:40,630] {logging_mixin.py:115} INFO - [2024-10-04 23:41:40,630] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:41:40,652] {logging_mixin.py:115} INFO - [2024-10-04 23:41:40,649] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:41:40,653] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:41:41,158] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.547 seconds
[2024-10-04 23:42:12,539] {processor.py:153} INFO - Started process (PID=99695) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:42:13,026] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:42:13,027] {logging_mixin.py:115} INFO - [2024-10-04 23:42:13,027] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:42:13,042] {logging_mixin.py:115} INFO - [2024-10-04 23:42:13,040] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:42:13,042] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:42:13,658] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.126 seconds
[2024-10-04 23:42:29,311] {processor.py:153} INFO - Started process (PID=99744) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:42:29,538] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:42:29,539] {logging_mixin.py:115} INFO - [2024-10-04 23:42:29,539] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:42:29,548] {logging_mixin.py:115} INFO - [2024-10-04 23:42:29,546] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:42:29,548] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:42:34,571] {processor.py:164} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 155, in _run_file_processor
    result: Tuple[int, int] = dag_file_processor.process_file(
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 654, in process_file
    self.update_import_errors(session, dagbag)
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 541, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2683, in all
    return self._iter().all()
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2818, in _iter
    result = self.session.execute(
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/kennedy/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT import_error.filename AS import_error_filename 
FROM import_error]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2024-10-04 23:43:26,991] {processor.py:153} INFO - Started process (PID=99814) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:43:27,006] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:43:27,008] {logging_mixin.py:115} INFO - [2024-10-04 23:43:27,007] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:43:27,024] {logging_mixin.py:115} INFO - [2024-10-04 23:43:27,022] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:43:27,025] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:43:28,469] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.484 seconds
[2024-10-04 23:43:40,980] {processor.py:153} INFO - Started process (PID=99828) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:43:41,130] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:43:41,131] {logging_mixin.py:115} INFO - [2024-10-04 23:43:41,131] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:43:41,144] {logging_mixin.py:115} INFO - [2024-10-04 23:43:41,143] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:43:41,145] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:43:41,387] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.414 seconds
[2024-10-04 23:44:18,471] {processor.py:153} INFO - Started process (PID=99876) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:44:18,987] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:44:18,988] {logging_mixin.py:115} INFO - [2024-10-04 23:44:18,988] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:44:19,012] {logging_mixin.py:115} INFO - [2024-10-04 23:44:19,010] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:44:19,013] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:44:19,366] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.903 seconds
[2024-10-04 23:44:20,272] {processor.py:153} INFO - Started process (PID=99877) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:44:20,273] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:44:20,274] {logging_mixin.py:115} INFO - [2024-10-04 23:44:20,274] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:44:20,288] {logging_mixin.py:115} INFO - [2024-10-04 23:44:20,286] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:44:20,289] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:44:21,272] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.007 seconds
[2024-10-04 23:44:42,643] {processor.py:153} INFO - Started process (PID=99990) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:44:43,431] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:44:43,432] {logging_mixin.py:115} INFO - [2024-10-04 23:44:43,431] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:44:43,445] {logging_mixin.py:115} INFO - [2024-10-04 23:44:43,443] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:44:43,446] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:44:43,821] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.184 seconds
[2024-10-04 23:45:11,598] {processor.py:153} INFO - Started process (PID=100124) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:45:11,609] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:45:11,609] {logging_mixin.py:115} INFO - [2024-10-04 23:45:11,609] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:45:11,615] {logging_mixin.py:115} INFO - [2024-10-04 23:45:11,614] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:45:11,615] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:45:12,150] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.555 seconds
[2024-10-04 23:45:19,345] {processor.py:153} INFO - Started process (PID=100177) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:45:19,346] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:45:19,347] {logging_mixin.py:115} INFO - [2024-10-04 23:45:19,347] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:45:19,678] {logging_mixin.py:115} INFO - 
####### Class init: 2024-10-04 23:45:19 #######
[2024-10-04 23:45:19,678] {logging_mixin.py:115} INFO - Scrapping...
[2024-10-04 23:45:19,679] {logging_mixin.py:115} INFO - [2024-10-04 23:45:19,679] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-04 23:45:19,764] {logging_mixin.py:115} INFO - [2024-10-04 23:45:19,764] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:45:20,036] {logging_mixin.py:115} INFO - [2024-10-04 23:45:20,036] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:45:20,215] {logging_mixin.py:115} INFO - [2024-10-04 23:45:20,215] {logger.py:11} INFO - Driver [/home/kennedy/.wdm/drivers/chromedriver/linux64/129.0.6668.89/chromedriver-linux64/chromedriver] found in cache
[2024-10-04 23:45:49,349] {logging_mixin.py:115} INFO - [2024-10-04 23:45:49,349] {timeout.py:67} ERROR - Process timed out, PID: 100177
[2024-10-04 23:45:49,349] {logging_mixin.py:115} INFO - Erro ao acessar https://letterboxd.com/film/la-la-land/: DagBag import timeout for /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#reducing-dag-complexity, PID: 100177
[2024-10-04 23:46:18,895] {processor.py:153} INFO - Started process (PID=101026) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:46:18,897] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:46:18,898] {logging_mixin.py:115} INFO - [2024-10-04 23:46:18,898] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:46:18,918] {logging_mixin.py:115} INFO - [2024-10-04 23:46:18,916] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:46:18,919] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:46:19,697] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.813 seconds
[2024-10-04 23:47:20,346] {processor.py:153} INFO - Started process (PID=101274) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:47:20,485] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:47:20,486] {logging_mixin.py:115} INFO - [2024-10-04 23:47:20,486] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:47:20,501] {logging_mixin.py:115} INFO - [2024-10-04 23:47:20,499] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:47:20,501] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:47:20,898] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.560 seconds
[2024-10-04 23:48:22,296] {processor.py:153} INFO - Started process (PID=101621) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:48:22,311] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:48:22,312] {logging_mixin.py:115} INFO - [2024-10-04 23:48:22,311] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:48:22,325] {logging_mixin.py:115} INFO - [2024-10-04 23:48:22,324] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:48:22,326] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:48:23,662] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.373 seconds
[2024-10-04 23:48:25,705] {processor.py:153} INFO - Started process (PID=101624) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:48:25,706] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:48:25,707] {logging_mixin.py:115} INFO - [2024-10-04 23:48:25,707] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:48:26,056] {logging_mixin.py:115} INFO - 
####### Class init: 2024-10-04 23:48:26 #######
[2024-10-04 23:48:26,056] {logging_mixin.py:115} INFO - Scrapping...
[2024-10-04 23:48:26,056] {logging_mixin.py:115} INFO - [2024-10-04 23:48:26,056] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-04 23:48:26,142] {logging_mixin.py:115} INFO - [2024-10-04 23:48:26,141] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:48:26,334] {logging_mixin.py:115} INFO - [2024-10-04 23:48:26,333] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-04 23:48:26,529] {logging_mixin.py:115} INFO - [2024-10-04 23:48:26,529] {logger.py:11} INFO - Driver [/home/kennedy/.wdm/drivers/chromedriver/linux64/129.0.6668.89/chromedriver-linux64/chromedriver] found in cache
[2024-10-04 23:48:55,709] {logging_mixin.py:115} INFO - [2024-10-04 23:48:55,709] {timeout.py:67} ERROR - Process timed out, PID: 101624
[2024-10-04 23:48:55,710] {logging_mixin.py:115} INFO - Erro ao acessar https://letterboxd.com/film/la-la-land/: DagBag import timeout for /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.2/best-practices.html#reducing-dag-complexity, PID: 101624
[2024-10-04 23:49:30,982] {processor.py:153} INFO - Started process (PID=102340) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:49:30,996] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:49:30,997] {logging_mixin.py:115} INFO - [2024-10-04 23:49:30,997] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:49:31,015] {logging_mixin.py:115} INFO - [2024-10-04 23:49:31,013] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:49:31,016] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:49:31,768] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.793 seconds
[2024-10-04 23:50:33,693] {processor.py:153} INFO - Started process (PID=102421) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:50:33,811] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:50:33,813] {logging_mixin.py:115} INFO - [2024-10-04 23:50:33,812] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:50:33,827] {logging_mixin.py:115} INFO - [2024-10-04 23:50:33,825] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:50:33,828] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:50:34,131] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.445 seconds
[2024-10-04 23:51:32,719] {processor.py:153} INFO - Started process (PID=102683) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:51:32,796] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:51:32,797] {logging_mixin.py:115} INFO - [2024-10-04 23:51:32,797] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:51:32,811] {logging_mixin.py:115} INFO - [2024-10-04 23:51:32,809] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:51:32,812] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:51:33,608] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.896 seconds
[2024-10-04 23:52:19,956] {processor.py:153} INFO - Started process (PID=102832) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:52:20,007] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:52:20,008] {logging_mixin.py:115} INFO - [2024-10-04 23:52:20,008] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:52:20,024] {logging_mixin.py:115} INFO - [2024-10-04 23:52:20,022] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:52:20,024] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:52:21,525] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.575 seconds
[2024-10-04 23:53:00,524] {processor.py:153} INFO - Started process (PID=102869) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:53:01,034] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:53:01,035] {logging_mixin.py:115} INFO - [2024-10-04 23:53:01,035] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:53:01,051] {logging_mixin.py:115} INFO - [2024-10-04 23:53:01,049] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:53:01,052] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:53:02,675] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 2.159 seconds
[2024-10-04 23:53:46,540] {processor.py:153} INFO - Started process (PID=103705) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:53:46,627] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:53:46,628] {logging_mixin.py:115} INFO - [2024-10-04 23:53:46,628] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:53:46,643] {logging_mixin.py:115} INFO - [2024-10-04 23:53:46,641] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:53:46,644] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:53:47,227] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.695 seconds
[2024-10-04 23:54:43,745] {processor.py:153} INFO - Started process (PID=103890) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:54:44,619] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:54:44,620] {logging_mixin.py:115} INFO - [2024-10-04 23:54:44,620] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:54:44,636] {logging_mixin.py:115} INFO - [2024-10-04 23:54:44,634] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:54:44,636] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:54:45,893] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 2.155 seconds
[2024-10-04 23:55:35,830] {processor.py:153} INFO - Started process (PID=103971) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:55:35,834] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:55:35,835] {logging_mixin.py:115} INFO - [2024-10-04 23:55:35,835] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:55:35,851] {logging_mixin.py:115} INFO - [2024-10-04 23:55:35,849] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:55:35,851] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:55:36,636] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.813 seconds
[2024-10-04 23:56:40,934] {processor.py:153} INFO - Started process (PID=104986) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:56:41,068] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:56:41,070] {logging_mixin.py:115} INFO - [2024-10-04 23:56:41,070] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:56:41,092] {logging_mixin.py:115} INFO - [2024-10-04 23:56:41,090] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:56:41,092] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:56:42,232] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.306 seconds
[2024-10-04 23:57:44,247] {processor.py:153} INFO - Started process (PID=105212) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:57:44,425] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:57:44,426] {logging_mixin.py:115} INFO - [2024-10-04 23:57:44,426] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:57:44,442] {logging_mixin.py:115} INFO - [2024-10-04 23:57:44,440] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:57:44,442] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:57:45,335] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.096 seconds
[2024-10-04 23:58:43,856] {processor.py:153} INFO - Started process (PID=105301) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:58:43,936] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:58:43,938] {logging_mixin.py:115} INFO - [2024-10-04 23:58:43,938] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:58:43,961] {logging_mixin.py:115} INFO - [2024-10-04 23:58:43,959] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:58:43,962] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:58:44,472] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.622 seconds
[2024-10-04 23:59:38,546] {processor.py:153} INFO - Started process (PID=105445) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:59:38,570] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-04 23:59:38,571] {logging_mixin.py:115} INFO - [2024-10-04 23:59:38,571] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:59:38,586] {logging_mixin.py:115} INFO - [2024-10-04 23:59:38,584] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-04 23:59:38,587] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-04 23:59:39,942] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 1.403 seconds
[2024-10-05 00:00:34,985] {processor.py:153} INFO - Started process (PID=105613) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-05 00:00:35,044] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-05 00:00:35,045] {logging_mixin.py:115} INFO - [2024-10-05 00:00:35,045] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-05 00:00:35,062] {logging_mixin.py:115} INFO - [2024-10-05 00:00:35,060] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-05 00:00:35,063] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-05 00:00:35,665] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.687 seconds
[2024-10-05 00:01:21,447] {processor.py:153} INFO - Started process (PID=105747) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-05 00:01:21,519] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-05 00:01:21,521] {logging_mixin.py:115} INFO - [2024-10-05 00:01:21,520] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-05 00:01:21,536] {logging_mixin.py:115} INFO - [2024-10-05 00:01:21,534] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-05 00:01:21,536] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-05 00:01:22,043] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 0.603 seconds
[2024-10-05 00:01:59,999] {processor.py:153} INFO - Started process (PID=105911) to work on /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-05 00:02:00,019] {processor.py:641} INFO - Processing file /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py for tasks to queue
[2024-10-05 00:02:00,020] {logging_mixin.py:115} INFO - [2024-10-05 00:02:00,020] {dagbag.py:507} INFO - Filling up the DagBag from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-05 00:02:00,037] {logging_mixin.py:115} INFO - [2024-10-05 00:02:00,035] {dagbag.py:320} ERROR - Failed to import: /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
Traceback (most recent call last):
  File "/home/kennedy/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py", line 7, in <module>
    from selenium.webdriver.chrome.service import Service as ChromeService
ModuleNotFoundError: No module named 'selenium'
[2024-10-05 00:02:00,038] {processor.py:653} WARNING - No viable dags retrieved from /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py
[2024-10-05 00:02:02,203] {processor.py:161} INFO - Processing /home/kennedy/KR/Programação/01.Exercícios/DE/Movies/MovieStats/airflow/dags/movieDag.py took 2.213 seconds
